const primary = [
  ["Primary 500", "#F97316", "p500"],
  ["Primary 400", "#FB923C", "p400"],
  ["Primary 300", "#FDBA74", "p300"],
  ["Primary 200", "#FED7AA", "p200"],
  ["Primary 100", "#FFEEE5", "p100"],
];
const neutral = [
  ["Neutral 900", "#0F172A", "n900"], ["Neutral 700", "#334155", "n700"],
  ["Neutral 500", "#64748B", "n500"], ["Neutral 300", "#CBD5E1", "n300"],
  ["Neutral 200", "#E2E8F0", "n200"], ["Neutral 100", "#F1F5F9", "n100"],
  ["Neutral 50", "#FAFAFC", "n50"], ["White", "#FFFFFF", "white"],
];
const Icon = ({ name, filled = false }: { name: string; filled?: boolean }) => (
  <span className={`icon ${filled ? "filled" : ""}`} aria-label={name}>{name === "arrow" ? "›" : name === "play" ? "⊙" : name === "check" ? "✓" : name === "clock" ? "◷" : name === "lock" ? "♙" : name === "user" ? "♙" : name === "search" ? "⌕" : name === "eye" ? "◎" : name === "grid" ? "▦" : name === "target" ? "◎" : name === "access" ? "♿" : "▧"}</span>
);
const Section = ({ number, title, children, className = "" }: { number: string; title: string; children: React.ReactNode; className?: string }) => (
  <section className={`panel ${className}`}><div className="section-head"><b>{number}</b><h2>{title}</h2></div>{children}</section>
);
const Label = ({ children }: { children: React.ReactNode }) => <div className="label">{children}</div>;

export default function DesignSytem() {
  return <main className="design-page">
    <div className="intro panel"><div className="intro-copy"><div className="brand"><span className="vertex-mark">▼</span><strong>Vertex</strong></div><h1>Design System</h1><p>A unified design language for Vertex<br />learning platform. Clean, modern and<br />focused on clarity, consistency and<br />intuitive learning experiences.</p><div className="version">VERSION 1.0 <i /> MAY 2025</div></div><Section number="01" title="COLORS" className="colors"><Label>Primary</Label><div className="swatches">{primary.map(([name, hex, tone]) => <div className="swatch" key={name}><span className={`color ${tone}`} /><small>{name}</small><em>{hex}</em></div>)}</div><Label>Neutral</Label><div className="swatches">{neutral.map(([name, hex, tone]) => <div className="swatch" key={name}><span className={`color ${tone}`} /><small>{name}</small><em>{hex}</em></div>)}</div></Section></div>

    <div className="row row-two"><Section number="02" title="TYPOGRAPHY"><div className="type-samples"><div className="type-preview serif">Ag</div><div><h3>Playfair Display</h3><p>Elegant <b /> Readable <b /> Timeless</p></div><div className="type-preview sans">Ag</div><div><h3>Inter</h3><p>Clean <b /> Modern <b /> Highly legible</p></div></div></Section><Section number="03" title="TYPE SCALE" className="scale"><div className="scale-grid header"><span>Style</span><span>Font</span><span>Size / Line Height</span><span>Weight</span><span>Use</span></div>{[["Display 1","Playfair Display","48 / 56","Bold","Page titles"],["Display 2","Playfair Display","36 / 44","Bold","Section titles"],["Heading 1","Inter","28 / 36","Semi Bold","Card titles"],["Heading 2","Inter","22 / 30","Semi Bold","Sub section"],["Heading 3","Inter","18 / 26","Medium","Small titles"],["Body Large","Inter","16 / 24","Regular","Body copy"],["Body","Inter","14 / 20","Regular","Supporting text"],["Small","Inter","12 / 16","Regular","Captions, meta"]].map(row => <div className="scale-grid" key={row[0]}>{row.map((cell, i) => <span className={i === 0 ? "scale-name" : ""} key={cell}>{cell}</span>)}</div>)}</Section></div>

    <div className="row row-three"><Section number="04" title="SPACING SYSTEM"><p className="subline">Base unit: 4px</p><div className="spacing">{[["4","0.25rem"],["8","0.5rem"],["12","0.75rem"],["16","1rem"],["24","1.5rem"],["32","2rem"],["40","2.5rem"],["48","3rem"],["64","4rem"]].map(([n, rem]) => <div key={n}><span className={`space s${n}`} /><b>{n}</b><small>{rem}</small></div>)}</div></Section><Section number="05" title="RADIUS & SHADOWS"><Label>Radius</Label><div className="radii">{[["4px","(xs)"],["8px","(sm)"],["12px","(md)"],["16px","(lg)"],["24px","(xl)"],["Full","(circle)"]].map(([n, sub], i) => <div key={n}><span className={`radius r${i}`} /><small>{n}<br />{sub}</small></div>)}</div><Label>Shadows</Label><div className="shadows">{[["Sm","0 1px 2px 0 rgba(15, 23, 42, 0.05)"],["Md","0 4px 12px -2px rgba(15, 23, 42, 0.08)"],["Lg","0 12px 24px -4px rgba(15, 23, 42, 0.10)"],["Xl","0 20px 40px -8px rgba(15, 23, 42, 0.12)"]].map(([n, value]) => <div key={n}><b>{n}</b><small>{value}</small></div>)}</div></Section></div>

    <div className="row row-three lower"><Section number="06" title="ICONS"><Label>Outline Style</Label><div className="icon-row">{["bell","search","play","file","bookmark","chart","clock","user","arrow"].map(n => <Icon name={n} key={n} />)}</div><Label>Filled Style</Label><div className="icon-row">{["bell","search","play","file","bookmark","chart","clock","user","arrow"].map(n => <Icon name={n} filled key={n} />)}</div><Label>Icon Specs</Label><ul><li>24x24px size</li><li>2px stroke width (outline)</li><li>Rounded line caps</li><li>Consistent optical balance</li></ul></Section><Section number="07" title="BUTTONS" className="buttons"><div className="button-head"><span /><span>Primary</span><span>Secondary</span><span>Tertiary</span><span>Text</span></div>{[["Default","btn-primary","Get Started","btn-secondary","Explore Courses","btn-tertiary","View Lesson ↗","btn-text","Watch Video ◉"],["Hover","btn-primary hover","Get Started","btn-secondary hover","Explore Courses","btn-tertiary hover","View Lesson ↗","btn-text hover","Watch Video ◉"],["Disabled","btn-primary disabled","Get Started","btn-secondary disabled","Explore Courses","btn-tertiary disabled","View Lesson ↗","btn-text disabled","Watch Video ◉"]].map(row => <div className="button-line" key={row[0]}><small>{row[0]}</small><button className={row[1]}>{row[2]}</button><button className={row[3]}>{row[4]}</button><button className={row[5]}>{row[6]}</button><button className={row[7]}>{row[8]}</button></div>)}<Label>Button Specs</Label><ul><li>Height: 44px (default)</li><li>Padding: 0 16px (lg), 0 12px (md)</li><li>Radius: 12px</li><li>Font: Inter Medium (14–16px)</li></ul></Section><Section number="08" title="INPUTS"><Label>Search / Text Input</Label><div className="input"><Icon name="search" /><span>Search anything...</span><kbd>⌘ K</kbd></div><Label>Select</Label><div className="input select">Most Relevant <span>⌄</span></div><Label>Field Specs</Label><ul><li>Height: 44px</li><li>Radius: 12px</li><li>Border: 1px solid #E2E8F0</li><li>Padding: 0 16px</li><li>Focus: Border color #FB923C</li></ul></Section></div>

    <div className="mini-row"><Section number="09" title="BADGES / TAGS"><div className="badge-grid"><div><Label>Video</Label><mark className="badge video">VIDEO</mark></div><div><Label>Lesson</Label><mark className="badge lesson">LESSON</mark></div><div><Label>Popular</Label><mark className="badge popular">POPULAR</mark></div></div></Section><Section number="10" title="STATUS / INDICATORS"><div className="statuses"><span className="progress-dot" /> In Progress <span className="complete">✓</span> Completed <span className="now">▶</span> Now Playing <Icon name="lock" /> Locked</div></Section><Section number="11" title="PROGRESS BAR"><div className="progress"><span /><b>35%</b> complete</div></Section></div>

    <Section number="12" title="CARDS" className="cards-section"><div className="cards"><article className="course-card"><Label>Course Card</Label><div className="course-title"><span className="n-logo">N</span><div><b>Next.js for Production</b><p>Build scalable, high-performance<br />web applications with Next.js.</p></div></div><footer>▥ Intermediate　 ◷ 18h 24m　 ▱ 12 modules</footer></article><article className="lesson-card"><Label>Lesson Card (Video)</Label><mark className="badge video">VIDEO</mark><b>Data Fetching in Server Components</b><p>Learn how to fetch data on the server using<br />async/await and Next.js best practices.</p><footer>Lesson 5.1　·　12:45 <a>◉ Watch from 12:45</a></footer></article><article className="lesson-card"><Label>Lesson Card (Lesson)</Label><mark className="badge lesson">LESSON</mark><b>Data Fetching & Caching</b><p>Explore different data fetching methods<br />in Next.js and how to cache and revalidate<br />data for optimal performance.</p><footer>Module 5 <a>View lesson　↗</a></footer></article><article className="resource-card"><Label>Resource Card</Label><b>▧　 Caching and Revalidation Guide</b><p>Deep dive into Next.js caching strategies.</p><footer>PDF　·　1.2 MB <a>↗</a></footer></article></div></Section>

    <Section number="13" title="NAVIGATION" className="navigation"><div className="nav-samples"><div className="nav-bar"><strong><span className="vertex-mark">▼</span> Vertex</strong><a>Courses</a><a>My Learning</a></div><div><Label>Breadcrumbs</Label><p>All Courses　›　 Next.js for Production　›　 Data Fetching & Caching</p></div><div><Label>Pagination</Label><p>‹　 <b>1</b>　2　 3　 …　 8　 ›</p></div></div></Section>
    <Section number="14" title="PRINCIPLES" className="principles"><div><Icon name="eye" /><b>Clarity First</b><p>Every element should<br />communicate clearly.</p></div><div><Icon name="grid" /><b>Consistency</b><p>Use components and patterns<br />consistently across the platform.</p></div><div><Icon name="target" /><b>Focus & Calm</b><p>Remove noise and help learners<br />focus on what matters.</p></div><div><Icon name="access" /><b>Accessible</b><p>Design with accessibility<br />and inclusivity in mind.</p></div></Section>
  </main>;
}
